name: Update Submodules

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Update submodules
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git submodule update --remote --force
      
      - name: Commit changes
        run: |
          git add .
          if git diff --staged --quiet; then
            echo "Keine Änderungen"
          else
            git commit -m "🤖 Auto-update submodules [$(date +'%Y-%m-%d')]"
            git push
          fi
